services:
  - type: web
    name: bcra-proxy
    env: python
    buildCommand: pip install -r requisitos.txt
    startCommand: gunicorn main:app --timeout 120 --workers 1 --bind 0.0.0.0:8080
    envVars:
      - key: GEMINI_API_KEY
        sync: false
